name: DAST

on:
  repository_dispatch:
    types: [dast-ais-ng-repository-dispatch]

jobs:
  zap_scan:
    name: Scan the web application with DAST

    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/dast.yml@main
    with:
      TARGET_URL: 'https://white-sea-0feb97210.1.azurestaticapps.net/'
    secrets:
      TOKEN : ${{ secrets.GITHUB_TOKEN }}

  repository-dispatch:
    name: Repository dispatch
    needs: zap_scan

    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/repository-dispatch.yml@main
    with:
      REPOSITORY: 'kubeopsskills-enterprise/man-ng'
      EVENT_TYPE: 'uat-ais-ng-repository-dispatch'
      SHA: ${GITHUB_SHA}
    secrets:
      PAT : ${{ secrets.ORG_PAT  }}