name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  APP_NAME: man-ng
    
jobs:
  # unit-tests:
  #   name: Unit tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #         cache: 'npm'
  #         cache-dependency-path: ./package-lock.json

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run unit tests
  #       run: npm run test -- --no-watch --browsers=ChromeHeadlessCI --code-coverage

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage-report
  #         path: ./coverage

  # code-ql:
  #   name: CodeQL
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: [ 'javascript' ]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Initialize CodeQL
  #     uses: github/codeql-action/init@v1
  #     with:
  #       languages: ${{ matrix.language }}

  #   - name: Autobuild
  #     uses: github/codeql-action/autobuild@v1

  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact for deployment job
        run: |
          zip artifact-${GITHUB_SHA}.zip -r ./dist/${{ env.APP_NAME }}
          rm -rf ./dist/${{ env.APP_NAME }}
          az storage blob upload -c build -n artifact-${GITHUB_SHA}.zip -f ${GITHUB_WORKSPACE}/artifact-${GITHUB_SHA}.zip --connection-string "${{ secrets.BUILD_STORAGE_ACCOUNT_CONNECTION_STRING }}"
          rm artifact-${GITHUB_SHA}.zip

      - name: Save artifact name to develop branch
        run: |
          echo artifact-${GITHUB_SHA}.zip > latest-build-artifact
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "save latest artifact build name on Develop workflow [skip ci]"
          git push

  repository-dispatch:
    name: Repository dispatch
    needs: build

    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/repository-dispatch.yml@main
    with:
      REPOSITORY: 'kubeopsskills-enterprise/ais-share-pipeline'
      EVENT_TYPE: 'dev-ais-ng-repository-dispatch'
      SHA: ${GITHUB_SHA}
    secrets:
      PAT : ${{ secrets.PAT  }}
    
    # runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v2
    #     with:
    #       repository: 'kubeopsskills-enterprise/ais-share-pipeline'
          
    #   - name: Repository dispatch
    #     run: |
    #       DISPATCH_SHA=$(echo ${GITHUB_SHA})
    #       echo $DISPATCH_SHA
    #       DISPATCH_BODY=$(jq '.event_type |= "dev-ais-ng-repository-dispatch" | .client_payload.github_sha |= "'$DISPATCH_SHA'"' ./.github/template/env-repository-dispatch.json)
    #       curl -v --location --request POST 'https://api.github.com/repos/kubeopsskills-enterprise/man-ng-pipeline/dispatches' \
    #         --header 'Authorization: Bearer ${{ secrets.PAT }}' \
    #         --header 'accept: application/vnd.github.v3+json' \
    #         --header 'Content-Type: application/json' \
    #         --data-raw "$DISPATCH_BODY"
