name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  APP_NAME: man-ng
    
jobs:
  continuous-integration:
    name: Continuous Integration

    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/angular-develop-ci.yml@main
    with:
      APP_NAME: ${{ env.APP_NAME }}
    secrets:
      STORAGE_ACCOUNT_CONNECTION_STRING: ${{ secrets.BUILD_STORAGE_ACCOUNT_CONNECTION_STRING }}

  repository-dispatch:
    name: Repository dispatch
    needs: build

    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/repository-dispatch.yml@main
    with:
      REPOSITORY: 'kubeopsskills-enterprise/man-ng-pipeline'
      EVENT_TYPE: 'dev-ais-ng-repository-dispatch'
      SHA: ${GITHUB_SHA}
    secrets:
      PAT : ${{ secrets.PAT  }}