name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    
    steps:
      - uses: actions/checkout@v2

      - run: ls /dist/man-ng/

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - run: ls /dist/man-ng/

      - name: Run unit tests
        run: npm run test -- --no-watch --browsers=ChromeHeadlessCI --code-coverage

      - run: ls /dist/man-ng/

      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

  # code-ql:
  #   name: CodeQL
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: [ 'javascript' ]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Initialize CodeQL
  #     uses: github/codeql-action/init@v1
  #     with:
  #       languages: ${{ matrix.language }}

  #   - name: Autobuild
  #     uses: github/codeql-action/autobuild@v1

  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v1

  build_and_deploy:
    # needs: [unit-tests, code-ql]
    needs: [unit-tests]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2

      - run: ls /dist/man-ng/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MEADOW_00C345F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src/"
          output_location: "/dist/man-ng/"
          skip_app_build: true

  # build_and_deploy:
  #   needs: [unit-tests, code-ql]
  #   if: github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   name: Build and Deploy
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build And Deploy
  #       id: builddeploy
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MEADOW_00C345F10 }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         action: "upload"
  #         app_location: "/src/"
  #         output_location: "/dist/man-ng/"