name: SIT CI

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags'
        required: true 

jobs:
  retrieve-latest-artifact:
    name: Retrieve latest artifact
    
    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/retrieve-latest-built-sha.yml@main

  test:
    runs-on: ubuntu-latest

    steps:
    - run: echo ${{ github.event.base_ref }}

  dispatch-repository:
    name: Repository dispatch
    needs: retrieve-latest-artifact
    if: github.event.base_ref=='refs/heads/main'

    uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/repository-dispatch.yml@main
    with:
      REPOSITORY: 'kubeopsskills-enterprise/man-ng-pipeline'
      EVENT_TYPE: 'sit-ais-ng-repository-dispatch'
      SHA: $(echo ${{ needs.retrieve-latest-artifact.outputs.sha }} | awk 'match($0,/artifact-([a-z0-9]*).zip/,a) {print a[1]}')
    secrets:
      PAT : ${{ secrets.PAT  }}
